name: Add Account (JSON)

on:
  workflow_dispatch:
    inputs:
      account_name:
        description: 'Account Name'
        required: true
        type: string
      account_type:
        description: 'Account Type'
        required: true
        type: choice
        options:
          - free
          - premium
      account_password:
        description: 'Account Password'
        required: true
        type: string

jobs:
  add_account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Force accounts.json to be an array
        run: |
          if [ -f accounts.json ]; then
            if head -n1 accounts.json | grep -q '^{'; then
              mv accounts.json accounts.bak
              echo "[" > accounts.json
              cat accounts.bak >> accounts.json
              echo "]" >> accounts.json
            fi
          else
            echo "[]" > accounts.json
          fi

      - name: Add new account to accounts.json
        run: |
          jq '. += [{"name": "${{ github.event.inputs.account_name }}", "type": "${{ github.event.inputs.account_type }}", "password": "${{ github.event.inputs.account_password }}"}]' accounts.json > tmp.json
          mv tmp.json accounts.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add accounts.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add account: ${{ github.event.inputs.account_name }} (${{ github.event.inputs.account_type }})"
            git push
          fi
