name: Add Account (JSON)

on:
  workflow_dispatch:
    inputs:
      account_name:
        description: 'Account Name'
        required: true
        type: string
      account_type:
        description: 'Account Type'
        required: true
        type: choice
        options:
          - free
          - premium
      account_password:
        description: 'Account Password'
        required: true
        type: string

jobs:
  add_account:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Ensures GITHUB_TOKEN can push!

    steps:
      - uses: actions/checkout@v4

      - name: Ensure accounts.json is an array
        run: |
          if [ -f accounts.json ]; then
            if ! jq 'type == "array"' accounts.json | grep -q true; then
              echo "File is not a JSON array! Overwriting with empty array."
              echo "[]" > accounts.json
            fi
          else
            echo "[]" > accounts.json
          fi

      - name: Upsert account (unique by name)
        run: |
          jq --arg name "${{ github.event.inputs.account_name }}" \
             --arg type "${{ github.event.inputs.account_type }}" \
             --arg password "${{ github.event.inputs.account_password }}" '
            # Remove accounts with the same name, then add the new/updated one
            map(select(.name != $name)) +
            [{"name": $name, "type": $type, "password": $password}]
          ' accounts.json > tmp.json
          mv tmp.json accounts.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add accounts.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add or update account: ${{ github.event.inputs.account_name }} (${{ github.event.inputs.account_type }})"
            git push
          fi
